### ISSUE TITLE
Feedback for “Validator Upgrade Guide”

### ISSUE THREAD

**Issue by Brave-Humens** [webb-tools/tangle-docs#20]
Hello. I read your update guide .. And there are still many questions about what kind of keys are and where they are, how exactly and when I need to transfer them to a new one, and whether I need to do this if I just want to update the node to a new version. Can you describe in more detail, with an example, a guide for updating to a new version of the node? I will be very grateful to you

**Comment by salman01zp** [comment]
This are the keys required for running validator node on tangle
https://docs.tangle.tools/docs/node/validator/requirements/#2-generate-your-keys-and-import-them-to-the-keystore

And they are stored at  `/chains/Tangle/keystore`

But as stated in doc, If you need to upgrade Do not clone or copy the keystore; generate new keys for each validator instance.
https://docs.tangle.tools/docs/node/validator/upgrade-node/#keystore.

You can also refer Polkadot guidelines here https://wiki.polkadot.network/docs/maintain-guides-how-to-upgrade
